# Generated by Django 5.2.17 on 2026-09-07 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='relacionfamiliar',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='padres_tutores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relacionfamiliar',
            name='padre',
            field=models.ForeignKey(limit_choices_to={'rol': 'padre'}, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='relacionfamiliar',
            unique_together={('padre', 'alumno')},
        ),
    ]
